'use strict';
const board=document.querySelector('#game-board'), feedback=document.querySelector('#game-feedback'), play=document.querySelector('#play-button');
const modes={memory:{title:'Memory Mosaic',category:'VISUAL MEMORY',description:'Watch the glowing tiles, then select the same positions. Each round adds one more tile. Complete six rounds to master the mosaic.'},pattern:{title:'Pattern Detective',category:'LOGIC & PATTERNS',description:'Look for the rule connecting the numbers. Choose the missing value. Six puzzles, with an explanation after every answer.'},reaction:{title:'Signal Sprint',category:'REACTION TIME',description:'Wait for the pad to turn green, then click it or press Space as quickly as you can. Five rounds. An early click means a retry.'}};
let mode='memory',score=0,round=0,phase='ready',generation=0,timers=[],pattern=[],chosen=new Set(),puzzles=[],answered=false,signalAt=0,times=[];
function later(fn,ms){const token=generation;timers.push(setTimeout(()=>{if(token===generation)fn();},ms));}
function cancelTimers(){generation++;timers.forEach(clearTimeout);timers=[];}
function bestValue(){try{return Number(localStorage.getItem('my-arcade-'+mode))||0;}catch{return 0;}}
function saveBest(value,lower=false){const previous=bestValue();if(value>0&&(!previous||(lower?value<previous:value>previous))){try{localStorage.setItem('my-arcade-'+mode,String(value));}catch{}}updateStats();}
function updateStats(){document.querySelector('#score-label').textContent=mode==='reaction'?'LAST REACTION':'SCORE';document.querySelector('#score').textContent=mode==='reaction'?(times.length?times.at(-1)+' ms':'—'):score;const best=bestValue();document.querySelector('#best').textContent=best?(mode==='reaction'?best+' ms':best):'—';}
function message(text,error=false){feedback.textContent=text;feedback.classList.toggle('error',error);}
function setPlay(label,disabled=false){play.innerHTML='';const text=document.createElement('span');text.textContent=label;play.append(text);const arrow=document.createElement('span');arrow.textContent='→';play.append(arrow);play.disabled=disabled;}
function shuffle(array){for(let i=array.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[array[i],array[j]]=[array[j],array[i]];}return array;}
function random(min,max){return min+Math.floor(Math.random()*(max-min+1));}
function setRound(text){document.querySelector('#round-label').textContent=text;}
function selectMode(next){cancelTimers();mode=next;score=0;round=0;phase='ready';times=[];chosen.clear();document.querySelectorAll('[data-game]').forEach(b=>{const selected=b.dataset.game===mode;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});document.querySelector('.game-shell').className='game-shell game-'+mode;document.querySelector('#game-title').textContent=modes[mode].title;document.querySelector('#game-category').textContent=modes[mode].category;document.querySelector('#game-description').textContent=modes[mode].description;message('');setRound('Ready when you are');setPlay('Let’s play');updateStats();if(mode==='memory')renderMemory();if(mode==='pattern')board.innerHTML='<div class="pattern-sequence" aria-label="Example pattern"><span class="pattern-number">2</span><span class="pattern-number">4</span><span class="pattern-number">6</span><span class="pattern-number missing">?</span></div>';if(mode==='reaction')renderReaction('ready');}
function renderMemory(){board.innerHTML='<div class="memory-grid">'+Array.from({length:16},(_,i)=>`<button class="memory-tile" data-tile="${i}" aria-label="Tile row ${Math.floor(i/4)+1}, column ${i%4+1}" disabled></button>`).join('')+'</div>';board.querySelectorAll('[data-tile]').forEach(b=>b.addEventListener('click',()=>pickTile(Number(b.dataset.tile))));}
function memoryRound(){phase='show';chosen.clear();pattern=shuffle(Array.from({length:16},(_,i)=>i)).slice(0,round+2);renderMemory();pattern.forEach(i=>board.querySelector(`[data-tile="${i}"]`).classList.add('lit'));message(`Remember these ${pattern.length} tiles…`);setRound(`Round ${round} of 6`);setPlay('Remember the pattern',true);later(()=>{phase='pick';board.querySelectorAll('[data-tile]').forEach(b=>{b.classList.remove('lit');b.disabled=false;});message(`Your turn. Select all ${pattern.length} remembered tiles.`);},1800+round*100);}
function pickTile(index){if(phase!=='pick'||chosen.has(index))return;const tile=board.querySelector(`[data-tile="${index}"]`);if(!pattern.includes(index)){phase='ended';tile.classList.add('wrong');board.querySelectorAll('[data-tile]').forEach(b=>b.disabled=true);pattern.forEach(i=>board.querySelector(`[data-tile="${i}"]`).classList.add('lit'));message('That tile wasn’t in the pattern. The original tiles are shown. Give it another try!',true);saveBest(score);setPlay('Try again');return;}chosen.add(index);score+=10;tile.classList.add('chosen');tile.disabled=true;updateStats();message(`${chosen.size} of ${pattern.length} tiles found.`);if(chosen.size===pattern.length){score+=20;updateStats();saveBest(score);phase='round-done';message('Perfect recall! Every tile found.');board.querySelectorAll('[data-tile]').forEach(b=>b.disabled=true);if(round===6){phase='ended';message('Mosaic mastered! Six rounds complete. Brilliant memory.');setPlay('Play again');}else setPlay('Next round');}}
function createPuzzles(){const n=random(2,5),step=random(3,8),seed=random(1,6),f=random(1,4);return shuffle([
 {sequence:[seed,seed+step,seed+2*step,seed+3*step],answer:seed+4*step,explain:`Add ${step} each time.`},
 {sequence:[n,n*2,n*4,n*8],answer:n*16,explain:'Double each number.'},
 {sequence:[n*n,(n+1)**2,(n+2)**2,(n+3)**2],answer:(n+4)**2,explain:`Consecutive squares: ${n}², ${n+1}², ${n+2}², ${n+3}², ${n+4}².`},
 {sequence:[f,f+1,2*f+1,3*f+2],answer:5*f+3,explain:'Each number is the sum of the previous two.'},
 {sequence:[100,91,82,73],answer:64,explain:'Subtract 9 each time.'},
 {sequence:[3,6,10,15],answer:21,explain:'The gaps grow by one: +3, +4, +5, then +6.'}
 ]);}
function patternRound(){phase='answer';answered=false;const puzzle=puzzles[round-1];const distractors=new Set();while(distractors.size<3){const value=puzzle.answer+random(-12,12);if(value>=0&&value!==puzzle.answer)distractors.add(value);}const options=shuffle([puzzle.answer,...distractors]);board.innerHTML='<div class="pattern-sequence">'+puzzle.sequence.map((n,i)=>`<span class="pattern-number" style="animation-delay:${i*.06}s">${n}</span>`).join('')+'<span class="pattern-number missing" aria-label="Missing number">?</span></div><div class="pattern-options" role="group" aria-label="Choose the missing number">'+options.map(n=>`<button data-answer="${n}">${n}</button>`).join('')+'</div>';board.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(answered)return;answered=true;phase='round-done';const correct=Number(b.dataset.answer)===puzzle.answer;if(correct)score+=100;board.querySelectorAll('[data-answer]').forEach(option=>{option.disabled=true;if(Number(option.dataset.answer)===puzzle.answer)option.classList.add('correct');else if(option===b)option.classList.add('incorrect');});message(`${correct?'You found it!':'The answer is '+puzzle.answer+'.'} ${puzzle.explain}`,!correct);updateStats();saveBest(score);setPlay(round===6?'See my result':'Next puzzle');}));setRound(`Puzzle ${round} of 6`);message('What comes next?');setPlay('Choose an answer',true);}
function renderReaction(state){const text={ready:['ϟ','Catch the signal','Wait for green. Then click or press Space.'],waiting:['◎','Wait for it…','Stay ready. Don’t click yet.'],go:['ϟ','GO!','Click now or press Space.'],result:['✧','Nice catch!',times.length?times.at(-1)+' milliseconds':'']}[state];board.innerHTML=`<button class="reaction-pad ${state}" id="reaction-pad" ${state==='ready'?'disabled':''}><span class="signal-icon" aria-hidden="true">${text[0]}</span><span>${text[1]}</span><small>${text[2]}</small></button><div class="round-results">${times.map((ms,i)=>`<span>Round ${i+1}: ${ms} ms</span>`).join('')}</div>`;board.querySelector('#reaction-pad').addEventListener('click',react);}
function reactionRound(){phase='waiting';message('The wait changes each round. Watch the color.');setRound(`Round ${times.length+1} of 5`);setPlay('Waiting for signal',true);renderReaction('waiting');later(()=>{phase='go';signalAt=performance.now();renderReaction('go');message('Go!');},random(1600,3800));}
function react(){if(mode!=='reaction')return;if(phase==='waiting'){cancelTimers();phase='early';renderReaction('ready');message('Too soon! Wait for green. This attempt won’t count.',true);setPlay('Retry round');return;}if(phase==='go'){const elapsed=Math.max(1,Math.round(performance.now()-signalAt));times.push(elapsed);saveBest(elapsed,true);phase='round-done';renderReaction('result');message(elapsed<250?'Lightning quick!':elapsed<450?'Nice reflexes!':'Signal caught. Ready for another?');updateStats();setPlay(times.length===5?'See my result':'Next signal');}}
function finish(){phase='ended';if(mode==='pattern'){board.innerHTML=`<div class="end-celebration"><span aria-hidden="true">✳</span><h3>${score===600?'Pattern genius!':score>=400?'Sharp detective!':'Curiosity wins.'}</h3><p>You solved ${score/100} of 6 patterns.<br>A new mix awaits your next round.</p></div>`;message('');setRound('Six puzzles complete');}else{const avg=Math.round(times.reduce((a,b)=>a+b,0)/times.length);board.innerHTML=`<div class="end-celebration"><span aria-hidden="true">ϟ</span><h3>${avg} ms average</h3><p>Fastest signal: ${Math.min(...times)} ms.<br>Five rounds. One quick brain.</p></div><div class="round-results">${times.map(ms=>`<span>${ms} ms</span>`).join('')}</div>`;message('');setRound('Five signals caught');}setPlay('Play again');}
play.addEventListener('click',()=>{if(phase==='ready'||phase==='ended'){cancelTimers();score=0;round=1;times=[];updateStats();if(mode==='memory')memoryRound();if(mode==='pattern'){puzzles=createPuzzles();patternRound();}if(mode==='reaction')reactionRound();return;}if(mode==='memory'&&phase==='round-done'){round++;memoryRound();}if(mode==='pattern'&&phase==='round-done'){if(round===6)finish();else{round++;patternRound();}}if(mode==='reaction'){if(phase==='early')reactionRound();else if(phase==='round-done'){if(times.length===5)finish();else reactionRound();}}});
document.querySelectorAll('[data-game]').forEach(button=>button.addEventListener('click',()=>selectMode(button.dataset.game)));
document.addEventListener('keydown',e=>{if(mode==='reaction'&&e.code==='Space'&&(phase==='waiting'||phase==='go')&&!(e.target instanceof HTMLButtonElement&&e.target.id!=='reaction-pad')){e.preventDefault();if(!e.repeat)react();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='reaction'&&(phase==='waiting'||phase==='go')){cancelTimers();phase='early';renderReaction('ready');message('Paused while you were away. Retry this round when ready.');setPlay('Retry round');}});
selectMode('memory');
